= SkinTwitch - Marker Based Analysis of Skin Motion in Horses =

== Introduction ==

This is the cutaneous trunci skin twitch project.

== Current Status ==

Completed:

  - Power spectral analysis of initial trials.
  - Compute skin deformation gradient tensor from a marker grid.
  - Compute Biot & Green-Lagrangian strain from a marker grid.
  - Transformation of the stimulation device (poker), to find the position
     of its end point.
  - Computation of distance from poke point to marker grid mesh.
  - Final summary of results.

== Installation ==

Check out the project from GitHub (this command uses the Read-Only
repository):

  $ git clone git://github.com/lancelet/skintwitch.git

This will create a new directory called `skintwitch`.  Next, use
https://github.com/harrah/xsbt[sbt/xsbt] to compile the project:

  $ cd skintwitch
  $ sbt

https://github.com/harrah/xsbt[sbt/xsbt] will launch, and collect
everything it needs for the project.  Next, you must fetch the native library 
dependencies for VTK.  This is done for either Mac OS X or Linux using one of 
the commands:

  > vtkNativeOSX
  > vtkNativeLinux

These commands download compressed files containing the platform-specific
native dependencies, and then run processes to extract them into the `./lib`
directory.  This process for fetching the native dependencies may not be ideal
and will be revised if better options become available.  To run under Linux,
it may also be necessary to set the `LD_LIBRARY_PATH` environment variable
to the appropriate `./lib` subdirectory outside of sbt.

Within `sbt`, you can then run:

  > test

This will run the packaged unit tests for the project.
