= SkinTwitch - Marker Based Analysis of Skin Motion in Horses =

== Introduction ==

This is the cutaneous trunci skin twitch project.

== Current Status ==

Completed:
  - Power spectral analysis of initial trials.
Working on:
  - Computing the skin deformation gradient tensor.
  
== Installation ==

Check out the project from GitHub (this command uses the Read-Only
repository):

  $ git clone git://github.com/lancelet/skintwitch.git

This will create a new directory called `skintwitch`.  Next, use
https://github.com/harrah/xsbt[sbt/xsbt] to compile the project:

  $ cd skintwitch
  $ sbt

https://github.com/harrah/xsbt[sbt/xsbt] will launch, and collect
everything it needs for the project.  Within `sbt`, you can then run:

  > test

This will run the packaged unit tests for the project.

== NOTE: Problems with netlib-java-0.9.3.pom ==

If you encounter sha1 hash conflicts when fetching `netlib-java-0.9.0.pom` from
repo.scalanlp.org, a workaround is to checkout
https://github.com/scalala/Scalala[Scalala] from GitHub, and then run

  $ sbt update
 
It will then pull `netlib-java` into the Ivy cache, and sbt/xsbt will happily
use the cache version.